import boto3
import json
import time
import decimal

# connect to dynamoDB and write some helper functions for future use

dynamodb = boto3.resource('dynamodb', region_name='us-east-1')


def createTable():
    table = dynamodb.create_table(
        TableName='yelp-restaurants',
        KeySchema=[
            {
                'AttributeName': 'id',
                'KeyType': 'HASH'  # Partition key
            }
        ],
        AttributeDefinitions=[
            {
                'AttributeName': 'id',
                'AttributeType': 'S'
            }
        ],
        ProvisionedThroughput={
            'ReadCapacityUnits': 10,
            'WriteCapacityUnits': 10
        }
    )


# insert the data scraped from Yelp API
def storeData(data):
    table = dynamodb.Table('yelp-restaurants')
    with table.batch_writer() as batch:
        for d in data:
            batch.put_item(Item=d)


# get all data by restaurantID
def getData(id):
    table = dynamodb.Table('yelp-restaurants')
    response = table.get_item(
        Key={
            'id': id
        }
    )
    item = response['Item']
    return item


# load the json file generated by yelp.py
def loadJson():
    with open('../yelp/restaurant.json', 'r') as f:
         data = json.load(f, parse_float=decimal.Decimal)
    storeData(data)

def showCount():
    client = boto3.client('dynamodb', region_name='us-east-1')
    response = client.describe_table(TableName='yelp-restaurants')
    print(response)


loadJson()
